<?xml version="1.0" encoding="UTF-8"?>
<Export generator="Cache" version="25">
<Class name="Strix.JSON.PropertyParameters">
<TimeCreated>64394,79506.492902</TimeCreated>

<Parameter name="JSONNAME">
<Description>
The JSON name for this property; defaults to the Caché name
with the first letter lowercased.</Description>
</Parameter>

<Parameter name="JSONIO">
<Type>STRING</Type>
<Constraint>,IN,OUT,CALC,NONE</Constraint>
<Flags>ENUM</Flags>
</Parameter>
</Class>
</Export>
