name: Build release asset

on:
  release:
    types:
      - published

jobs:
  build-release-asset:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Strix
      uses: actions/checkout@v2
    
    - name: Checkout iris-export-builder
      uses: actions/checkout@v2
      with:
        repository: gertjanklein/iris-export-builder
        path: './ieb'
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install export builder dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r ieb/requirements.txt
    
    - name: Prepare UDL → XML conversion server
      run: |
        docker run --detach --rm -p 52773:52773 --name testiris containers.intersystems.com/intersystems/iris-community:2022.1.0.209.0 --check-caps false --up false
        docker cp ci/build.script testiris:/tmp/build.script
        docker exec testiris sh -c "iris start iris quietly && iris session iris < /tmp/build.script"
    
    - name: Build and zip the export
      run: |
        python ieb/src/build-export.py ci/build-export.toml
        mv ci/export.xml "Strix-${{ github.ref_name }}.xml"
        zip --junk-paths "Strix-${{ github.ref_name }}.zip" "Strix-${{ github.ref_name }}.xml"
    
    - name: Prepare UDL → XML conversion server
      run: docker stop testiris
    
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: Strix-${{ github.ref_name }}.zip
        asset_name: Strix-${{ github.ref_name }}.zip
        asset_content_type: application/zip
    
