name: Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: './strix'
    
    - run: docker build ci/ --file ci/Dockerfile --tag testiris
    - run: docker run -d --name testiris testiris --check-caps false --up false
    
    - run: docker cp ci/test.script testiris:/home/irisowner/test.script
    - run: docker cp strix/src testiris:/home/irisowner/src
    
    - run: docker exec testiris sh -c "iris start iris && iris session iris < /home/irisowner/test.script"
    
    - run: docker rm testiris --force
    - run: docker rmi testiris --force
