name: Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**'
      - 'ci/**'
      - '**.md'
      - 'LICENSE'
  
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - run: docker run --detach --rm --name testiris containers.intersystems.com/intersystems/iris-community:2023.1.1.380.0 --check-caps false --up false
    
    - run: docker cp ci/merge.cpf testiris:/home/irisowner/merge.cpf
    - run: docker cp ci/test.script testiris:/home/irisowner/test.script
    - run: docker cp src testiris:/home/irisowner/src
    
    - run: docker exec --env ISC_CPF_MERGE_FILE=/home/irisowner/merge.cpf testiris sh -c "iris start iris quietly >/dev/null && iris session iris < /home/irisowner/test.script"
    
    - run: docker stop testiris
